In [1]:
## Big-Box Retail Customer Behavior & Segmentation Analysis

### Business Objective
#Analyze customer purchase behavior for a big-box retail chain to identify
#high-value customers, churn-risk segments, and retention drivers, and recommend
#actions to improve customer retention and acquisition efficiency.

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [6]:
customers = pd.read_csv("C:/Users/roshn/Downloads/customers.csv")
transactions = pd.read_csv("C:/Users/roshn/Downloads/transactions.csv")

In [26]:
customers.head()

,customer_id,full_name,age,gender,email,phone,street_address,city,state,zip_code,registration_date,preferred_channel
0,4c30e132-0704-4459-a509-9eddde934977,Mark Johnson,40.0,Male,mark.johnson@yahoo.com,989.608.3863,819 Johnson Course,Houston,Texas,29158.0,4/25/2024,NaN
1,68bec407-275f-4b5b-9a82-13d02f54626a,Robert Smith,33.0,Male,smithr@yahoo.com,(518)349-5931x0341,35116 Michael Key Suite 078,Austin,Texas,16862.0,5/30/2021,in-store
2,4466459f-76c8-433c-814e-6d59cb4131fc,Jamie Chavez,42.0,Female,jchavez@gmail.com,364.583.5030x564,419 Amanda Gardens,Detroit,Michigan,21918.0,12/14/2023,online
3,04c36a25-02f3-462c-92b0-6bf291c57706,Thomas Bradley,53.0,Male,thomas.bradley@hotmail.com,(332)887-1012x269,7242 Julie Plain Suite 969,Fort Worth,Texas,52851.0,7/11/2022,both
4,e916df3d-c3f5-40b0-8ae2-5d043be88300,Jane Ferrell,32.0,Female,jane.ferrell@hotmail.com,5484281489,845 Kelly Estate,Atlanta,Georgia,59971.0,9/6/2020,online

In [8]:
transactions.head()

,transaction_id,customer_id,product_name,product_category,quantity,price,transaction_date,store_location,payment_method,discount_applied
0,53e3d9f5-6231-46de-aa39-e5f8eaae2eee,727839b2-f084-4e94-94d8-ae59cc8e4b84,Ring Doorbell,Smart Home Devices,1.0,140.07,2020-12-06,"Houston, TX",Credit Card,20.0
1,ae6e6edf-f2fe-45c8-989c-c01e77eade0c,c4ac244c-989e-46fb-b243-91dd1d5cf739,Oculus Quest,Gaming Consoles,1.0,339.57,2021-04-26,Online,Gift Card,0.0
2,ba85240a-2b5d-4987-ac0a-efb6a4a57d6d,d296bf0d-92bb-4670-a578-2fd3553cf7c8,Samsung Galaxy S22,Smartphones,2.0,1335.88,2021-10-28,Online,PayPal,30.0
3,3725a285-2a2b-4a80-b317-7c8041cd9b8b,7b1b9980-9d65-40fc-8ad6-6afaae4699e4,External Hard Drive,Computer Accessories,1.0,91.56,2023-03-16,Online,Credit Card,25.0
4,de1b05a5-68c7-4b00-a068-e8c2f13f0dab,8595dcfa-2bfc-46f4-a15a-042af85b78cd,MacBook Pro,Laptops,1.0,985.15,2022-08-30,"Atlanta, GA",Credit Card,0.0

In [9]:
customers.nunique()
#transactions.nunique()

customer_id          5000
full_name            4720
age                    57
gender                  4
email                4776
phone                4811
street_address       4823
city                   74
state                  15
zip_code             4789
registration_date    1711
preferred_channel       3
dtype: int64

In [10]:
transactions.nunique()

transaction_id      32295
customer_id          4618
product_name           75
product_category       15
quantity               45
price               27603
transaction_date     1761
store_location         11
payment_method          7
discount_applied        7
dtype: int64

In [11]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5000 non-null   object
 1   full_name          4894 non-null   object
 2   age                4814 non-null   float64
 3   gender             4888 non-null   object
 4   email              4889 non-null   object
 5   phone              4814 non-null   object
 6   street_address     4823 non-null   object
 7   city               4903 non-null   object
 8   state              4907 non-null   object
 9   zip_code           4904 non-null   float64
 10  registration_date  5000 non-null   object
 11  preferred_channel  4886 non-null   object
dtypes: float64(2), object(10)
memory usage: 468.9+ KB

In [12]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32295 entries, 0 to 32294
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    32295 non-null  object
 1   customer_id       32295 non-null  object
 2   product_name      31617 non-null  object
 3   product_category  31609 non-null  object
 4   quantity          31651 non-null  float64
 5   price             31673 non-null  float64
 6   transaction_date  32295 non-null  object
 7   store_location    31651 non-null  object
 8   payment_method    31635 non-null  object
 9   discount_applied  31684 non-null  float64
dtypes: float64(3), object(7)
memory usage: 2.5+ MB

In [13]:
transactions['transaction_date'].min(), transactions['transaction_date'].max()

('2020-03-04', '2025-02-25')

In [14]:
transactions.isna().sum().sort_values(ascending=False)

product_category    686
product_name        678
payment_method      660
quantity            644
store_location      644
price               622
discount_applied    611
transaction_id        0
customer_id           0
transaction_date      0
dtype: int64

In [15]:
##to find percentage of missing values in the dataset
(transactions.isna().mean() * 100).sort_values(ascending=False)

product_category    2.124168
product_name        2.099396
payment_method      2.043660
quantity            1.994117
store_location      1.994117
price               1.925995
discount_applied    1.891934
transaction_id      0.000000
customer_id         0.000000
transaction_date    0.000000
dtype: float64

In [16]:
purchase_counts = transactions.groupby('customer_id').size()

purchase_counts.describe()
##### Purchase Frequency Overview
##  Customers show meaningful variation in purchase behavior, with a median of 6 purchases and the top 25% 
##  purchasing 10 or more times. This distribution supports customer segmentation and retention analysis.

count    4618.000000
mean        6.993287
std         4.655161
min         1.000000
25%         3.000000
50%         6.000000
75%        10.000000
max        33.000000
dtype: float64

In [17]:
transactions.groupby('transaction_id').size().describe()

count    32295.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
dtype: float64

In [18]:
transactions['transaction_date'] = pd.to_datetime(transactions['transaction_date'])

In [19]:
transactions['sales_amount'] = transactions['quantity'] * transactions['price']

In [20]:
transactions.head()

,transaction_id,customer_id,product_name,product_category,quantity,price,transaction_date,store_location,payment_method,discount_applied,sales_amount
0,53e3d9f5-6231-46de-aa39-e5f8eaae2eee,727839b2-f084-4e94-94d8-ae59cc8e4b84,Ring Doorbell,Smart Home Devices,1.0,140.07,2020-12-06,"Houston, TX",Credit Card,20.0,140.07
1,ae6e6edf-f2fe-45c8-989c-c01e77eade0c,c4ac244c-989e-46fb-b243-91dd1d5cf739,Oculus Quest,Gaming Consoles,1.0,339.57,2021-04-26,Online,Gift Card,0.0,339.57
2,ba85240a-2b5d-4987-ac0a-efb6a4a57d6d,d296bf0d-92bb-4670-a578-2fd3553cf7c8,Samsung Galaxy S22,Smartphones,2.0,1335.88,2021-10-28,Online,PayPal,30.0,2671.76
3,3725a285-2a2b-4a80-b317-7c8041cd9b8b,7b1b9980-9d65-40fc-8ad6-6afaae4699e4,External Hard Drive,Computer Accessories,1.0,91.56,2023-03-16,Online,Credit Card,25.0,91.56
4,de1b05a5-68c7-4b00-a068-e8c2f13f0dab,8595dcfa-2bfc-46f4-a15a-042af85b78cd,MacBook Pro,Laptops,1.0,985.15,2022-08-30,"Atlanta, GA",Credit Card,0.0,985.15

In [21]:
df = transactions.merge(customers, on='customer_id', how='left')

In [22]:
df.head()

,transaction_id,customer_id,product_name,product_category,quantity,price,transaction_date,store_location,payment_method,discount_applied,...,age,gender,email,phone,street_address,city,state,zip_code,registration_date,preferred_channel
0,53e3d9f5-6231-46de-aa39-e5f8eaae2eee,727839b2-f084-4e94-94d8-ae59cc8e4b84,Ring Doorbell,Smart Home Devices,1.0,140.07,2020-12-06,"Houston, TX",Credit Card,20.0,...,33.0,Male,myersj@yahoo.com,001-348-825-3110x60920,62658 Samuel Courts Apt. 819,Miami,Florida,51882.0,6/1/2020,in-store
1,ae6e6edf-f2fe-45c8-989c-c01e77eade0c,c4ac244c-989e-46fb-b243-91dd1d5cf739,Oculus Quest,Gaming Consoles,1.0,339.57,2021-04-26,Online,Gift Card,0.0,...,18.0,Male,wgallegos@yahoo.com,232-769-8344x3695,775 Smith Pass,San Antonio,Texas,80317.0,2/9/2021,online
2,ba85240a-2b5d-4987-ac0a-efb6a4a57d6d,d296bf0d-92bb-4670-a578-2fd3553cf7c8,Samsung Galaxy S22,Smartphones,2.0,1335.88,2021-10-28,Online,PayPal,30.0,...,33.0,Male,athomas@yahoo.com,(881)343-6597x23976,2076 Scott Branch,NaN,Virginia,6280.0,10/22/2021,online
3,3725a285-2a2b-4a80-b317-7c8041cd9b8b,7b1b9980-9d65-40fc-8ad6-6afaae4699e4,External Hard Drive,Computer Accessories,1.0,91.56,2023-03-16,Online,Credit Card,25.0,...,40.0,Male,mcdowellj@yahoo.com,595-297-3725,546 Miller Circle Suite 906,Pittsburgh,Pennsylvania,14741.0,12/31/2020,online
4,de1b05a5-68c7-4b00-a068-e8c2f13f0dab,8595dcfa-2bfc-46f4-a15a-042af85b78cd,MacBook Pro,Laptops,1.0,985.15,2022-08-30,"Atlanta, GA",Credit Card,0.0,...,26.0,Male,tcain@hotmail.com,992.653.1411x247,8179 Mason River Suite 454,San Jose,California,68597.0,4/11/2022,in-store

In [23]:
analysis_date = df['transaction_date'].max()
analysis_date

Timestamp('2025-02-25 00:00:00')

In [24]:
rfm = (
    df
    .dropna(subset=['sales_amount'])  # exclude rows with null spend for Monetary
    .groupby('customer_id')
    .agg(
        recency_days = ('transaction_date', lambda x: (analysis_date - x.max()).days),
        frequency     = ('transaction_id', 'nunique'),
        monetary      = ('sales_amount', 'sum')
    )
    .reset_index()
)

rfm.head()

                            customer_id  recency_days  frequency  monetary
0  00012aa8-e99c-4e30-b3f6-1f7e36adc517            35          5   2734.46
1  000feeed-f931-4908-b539-29ab57e595be            94          6   2813.06
2  00107f62-0530-48ec-a56a-49d90944eafe            74          1    161.99
3  005ae094-2f68-4a6d-91f0-73b38b890692            70          6   3691.46
4  00a6835b-c50a-49a9-a1b5-19d74d3e1863            25          7   3820.98

In [25]:
## to check if there are any null values or not
rfm[['recency_days','frequency','monetary']].isna().sum()

recency_days    0
frequency       0
monetary        0
dtype: int64

In [30]:
rfm['recency_days'].describe()

count    4603.000000
mean      138.120356
std       149.919975
min         0.000000
25%        49.000000
50%        88.000000
75%       180.000000
max      1086.000000
Name: recency_days, dtype: float64

In [31]:
rfm['R_score'] = pd.qcut(rfm['recency_days'], 4, labels=[4,3,2,1]).astype(int)
rfm['F_score'] = pd.qcut(rfm['frequency'],    4, labels=[1,2,3,4]).astype(int)
rfm['M_score'] = pd.qcut(rfm['monetary'],     4, labels=[1,2,3,4]).astype(int)

rfm['RFM_score'] = rfm['R_score']*100 + rfm['F_score']*10 + rfm['M_score']

In [32]:
rfm.head()

,customer_id,recency_days,frequency,monetary,R_score,F_score,M_score,RFM_score
0,00012aa8-e99c-4e30-b3f6-1f7e36adc517,35,5,2734.46,4,2,2,422
1,000feeed-f931-4908-b539-29ab57e595be,94,6,2813.06,2,2,2,222
2,00107f62-0530-48ec-a56a-49d90944eafe,74,1,161.99,3,1,1,311
3,005ae094-2f68-4a6d-91f0-73b38b890692,70,6,3691.46,3,2,2,322
4,00a6835b-c50a-49a9-a1b5-19d74d3e1863,25,7,3820.98,4,3,2,432

In [36]:
conditions = [
    (rfm['R_score'] >= 3) & (rfm['F_score'] >= 3) & (rfm['M_score'] >= 3),
    (rfm['R_score'] >= 3) & (rfm['F_score'] <= 2),
    (rfm['R_score'] <= 2) & (rfm['F_score'] >= 3)
]

choices = [
    'High Value / Loyal',
    'New / Promising',
    'At Risk'
]

rfm['segment'] = np.select(conditions, choices, default='Low Engagement')

In [35]:
##rfm.drop(columns=['segment'], inplace=True)

In [45]:
rfm.head()

,customer_id,recency_days,frequency,monetary,R_score,F_score,M_score,RFM_score,segment
0,00012aa8-e99c-4e30-b3f6-1f7e36adc517,35,5,2734.46,4,2,2,422,New / Promising
1,000feeed-f931-4908-b539-29ab57e595be,94,6,2813.06,2,2,2,222,Low Engagement
2,00107f62-0530-48ec-a56a-49d90944eafe,74,1,161.99,3,1,1,311,New / Promising
3,005ae094-2f68-4a6d-91f0-73b38b890692,70,6,3691.46,3,2,2,322,New / Promising
4,00a6835b-c50a-49a9-a1b5-19d74d3e1863,25,7,3820.98,4,3,2,432,Low Engagement

In [38]:
segment_summary = (
    rfm
    .groupby('segment')
    .agg(
        customers = ('customer_id','count'),
        avg_recency_days = ('recency_days','mean'),
        avg_frequency = ('frequency','mean'),
        total_revenue = ('monetary','sum')
    )
    .reset_index()
)

segment_summary

,segment,customers,avg_recency_days,avg_frequency,total_revenue
0,At Risk,910,199.239560,10.434066,8.623868e+06
1,High Value / Loyal,1012,45.239130,11.471344,1.062339e+07
2,Low Engagement,1549,230.216914,3.826985,4.982072e+06
3,New / Promising,1132,46.000000,3.542403,3.562517e+06

In [40]:
### RFM Methodology
##  Customers were segmented using Recency (days since last purchase event),
##  Frequency (number of purchase events), and Monetary value (total spend).
##  Given the data structure, frequency represents purchase events rather than store visits.
##  RFM scores were computed using quartile-based thresholds to ensure robustness.

In [43]:
segment_summary['avg_recency_days'] = segment_summary['avg_recency_days'].round(2)
segment_summary['avg_frequency'] = segment_summary['avg_frequency'].round(2)
segment_summary['total_revenue'] = segment_summary['total_revenue'].round(2)

In [44]:
segment_summary

,segment,customers,avg_recency_days,avg_frequency,total_revenue
0,At Risk,910,199.24,10.43,8623867.95
1,High Value / Loyal,1012,45.24,11.47,10623387.29
2,Low Engagement,1549,230.22,3.83,4982072.31
3,New / Promising,1132,46.00,3.54,3562517.33

In [46]:
rfm['monetary'] = rfm['monetary'].round(2)
rfm.head()

,customer_id,recency_days,frequency,monetary,R_score,F_score,M_score,RFM_score,segment
0,00012aa8-e99c-4e30-b3f6-1f7e36adc517,35,5,2734.46,4,2,2,422,New / Promising
1,000feeed-f931-4908-b539-29ab57e595be,94,6,2813.06,2,2,2,222,Low Engagement
2,00107f62-0530-48ec-a56a-49d90944eafe,74,1,161.99,3,1,1,311,New / Promising
3,005ae094-2f68-4a6d-91f0-73b38b890692,70,6,3691.46,3,2,2,322,New / Promising
4,00a6835b-c50a-49a9-a1b5-19d74d3e1863,25,7,3820.98,4,3,2,432,Low Engagement

In [47]:
rfm.to_csv('C:/Users/roshn/Downloads/rfm_customer_level.csv', index=False)
segment_summary.to_csv('C:/Users/roshn/Downloads/rfm_segment_summary.csv', index=False)